// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyWebAPI.Database;

namespace MyWebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210630195815_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyWebAPI.Models.IPInfo", b =>
                {
                    b.Property<string>("StartIP")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EndIP")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IntermediateIP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StartIP", "EndIP");

                    b.ToTable("IPInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
